{{- if and .Values.podDisruptionBudget.enabled (gt (.Values.replicaCount|int) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "acl-operator.fullname" . }}
  labels:
    {{- include "acl-operator.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "acl-operator.selectorLabels" . | nindent 6 }}
{{- end }}
