apiVersion: apps/v1
kind: StatefulSet
metadata:
{{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
{{- end }}
  name: {{ include "buildkit.fullname" . }}
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "buildkit.fullname" . }}
  selector:
    matchLabels:
      {{- include "buildkit.selectorLabels" . | nindent 6 }}
  {{- with .Values.updateStategy }}
  updateStategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.volumeClaimTemplates }}
  volumeClaimTemplates: {{- toYaml . | nindent 2 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- with .Values.config }}
        buildkit.tsuru.io/checksum-buildkit-config: {{ sha256sum . }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "buildkit.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "buildkit.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: buildkit
        image: {{ .Values.image.repository }}:{{ default (printf "v%s" .Chart.AppVersion) .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /usr/bin/buildkitd
        {{- if .Values.config }}
        - --config=/etc/buildkit/buildkitd.toml
        {{- end }}
        ports:
        - name: http
          containerPort: 8080
        {{- with .Values.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe: {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.config }}
        - name: buildkit-config
          mountPath: /etc/buildkit/buildkitd.toml
          subPath: buildkitd.toml
        {{- end }}
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      {{- if .Values.config }}
      - name: buildkit-config
        configMap:
          name: {{ include "buildkit.configName" . }}
      {{- end }}
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 6 }}
      {{- end }}
