{{- if .Values.deployAgent.buildkit.autoDiscovery.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "deploy-agent.fullname" . }}
  labels:
    {{- include "deploy-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - tsuru.io
  resources:
  - apps
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "deploy-agent.fullname" . }}
  labels:
    {{- include "deploy-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "deploy-agent.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "deploy-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
